name: Build Latest Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Create an empty Cargo.lock file if it doesn't exist
      - name: Check for Cargo.lock
        run: |
          if [ ! -f "Cargo.lock" ]; then
            echo "Creating empty Cargo.lock file"
            touch Cargo.lock
          fi

      # Get the commit SHA for the tag
      - name: Get commit info
        id: commit_info
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "Using commit SHA: $SHA"

      # Build and push the latest image only
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/scarchive/archiver_webhook:latest
            ghcr.io/scarchive/archiver_webhook:${{ steps.commit_info.outputs.sha }}
          build-args: |
            VERSION=latest

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }} 